apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-webserver-ingress
  namespace: mueller-maximilian
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: mueller-maximilian.k8s.schoeppi5.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-webserver-service
            port:
              number: 80